// Copia só pra fazer mais rápido com os outros tênis
const modeloTenis = {
    id: 5,
    marca: "",
    modelo: "",
    nome: "",
    colorway: "/",
    preco: 0,
    desc: "",
    categorias: ["", ""],
    tamanhos: [30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43],
};

export const tenisArr = [
    {
        id: 1,
        marca: "Nike",
        modelo: "Air Force 1",
        nome: "Nike Air Force 1",
        colorway: "Triple White",
        preco: 90.0,
        desc: `O Nike Air Force 1 é um tênis icônico que combina estilo urbano com conforto duradouro. Lançado originalmente para o basquete, ele conquistou as ruas e a moda casual.`,
        categorias: ["Casual", "Clássico"],
        tamanhos: [34, 35, 36, 37, 38, 39, 40, 41, 42, 43],
    },
    {
        id: 2,
        marca: "Adidas",
        modelo: "Runfalcon 3.0",
        nome: "Adidas Runfalcon 3.0",
        colorway: "Preto/Branco",
        preco: 90.0,
        desc: `O Adidas Runfalcon 3.0 é um tênis versátil que combina desempenho esportivo com conforto para o dia a dia. Desenvolvido para corrida leve e caminhada, ele conta com cabedal em mesh respirável e entressola com amortecimento Cloudfoam, proporcionando leveza e maciez a cada passo. Com design moderno e discreto, é ideal tanto para treinos quanto para compor um visual casual confortável.`,
        categorias: ["Esportivo", "Corrida"],
        tamanhos: [34, 35, 36, 37, 38, 39, 40, 41, 42, 43],
    },
    {
        id: 3,
        marca: "Puma",
        modelo: "180",
        nome: "Puma 180",
        colorway: "Preto/Branco/Laranja",
        preco: 147.0,
        desc: `O Puma 180 combina estilo retrô dos anos 2000 com atitude street. Possui cabedal em camurça e mesh, oferecendo conforto, resistência e respirabilidade. A entressola macia garante amortecimento no dia a dia, enquanto o solado de borracha proporciona boa aderência. Ideal para quem busca visual marcante e conforto.`,
        categorias: ["Casual", "Streetwear"],
        tamanhos: [35, 36, 37, 38, 39],
    },
    {
        id: 4,
        marca: "Adidas",
        modelo: "Campus",
        nome: "Adidas Campus",
        colorway: "Preto/Branco",
        preco: 147.0,
        desc: `O Adidas Campus é um clássico atemporal que une estilo retrô e versatilidade. Com cabedal em camurça macia, ele oferece conforto e acabamento premium, enquanto as icônicas três listras laterais reforçam a identidade da marca. A entressola proporciona leve amortecimento para o dia a dia, e o solado de borracha garante boa aderência e durabilidade. Ideal para compor looks casuais e streetwear com autenticidade.`,
        categorias: ["Casual", "Clássico"],
        tamanhos: [38, 39, 40, 41, 42, 43],
    },
];
