export const tenisArr = [
    {
        id: 1,
        marca: "Nike",
        modelo: "Air Force 1",
        nome: "Nike Air Force 1",
        colorway: "Triple White",
        preco: 299.99,
        desc: `O Nike Air Force 1 é um tênis icônico que combina estilo urbano com conforto duradouro. Lançado originalmente para o basquete, ele conquistou as ruas e a moda casual.`,
        categorias: ["Casual", "Clássico"],
        tamanhos: [35, 36, 37, 38, 39, 40, 41, 42, 43],
    },
    {
        id: 2,
        marca: "Nike",
        modelo: "Zoom X",
        nome: "Nike Zoom X",
        colorway: "Triple White",
        preco: 299.99,
        desc: `O Nike Air Force 1 é um tênis icônico que combina estilo urbano com conforto duradouro. Lançado originalmente para o basquete, ele conquistou as ruas e a moda casual.`,
        categorias: ["Casual", "Clássico"],
        tamanhos: [35, 36, 37, 38, 39, 40, 41, 42, 43],
    },
    {
        id: 3,
        marca: "Nike",
        modelo: "Air Jordan 1",
        nome: "Nike Air Jordan 1",
        colorway: "Triple White",
        preco: 299.99,
        desc: `O Nike Air Force 1 é um tênis icônico que combina estilo urbano com conforto duradouro. Lançado originalmente para o basquete, ele conquistou as ruas e a moda casual.`,
        categorias: ["Casual", "Clássico"],
        tamanhos: [35, 36, 37, 38, 39, 40, 41, 42, 43],
    },
    {
        id: 3,
        marca: "Nike",
        modelo: "Air Jordan 1",
        nome: "Nike Air Jordan 1",
        colorway: "Triple White",
        preco: 299.99,
        desc: `O Nike Air Force 1 é um tênis icônico que combina estilo urbano com conforto duradouro. Lançado originalmente para o basquete, ele conquistou as ruas e a moda casual.`,
        categorias: ["Casual", "Clássico"],
        tamanhos: [35, 36, 37, 38, 39, 40, 41, 42, 43],
    },
];
